#!/usr/bin/env python3
"""Inject AI Humanizer i18n keys into all language files."""
import json, os

BASE = os.path.dirname(os.path.abspath(__file__))

EN_KEYS = {
  "ah.seo.title": "AI Humanizer — Convert AI Text to Human Writing Free | ToolboxNova",
  "ah.seo.desc": "Transform ChatGPT, Claude, Gemini AI text into natural human writing. Bypass GPTZero, Turnitin, Copyleaks. 6 modes, streaming output, free forever.",
  "ah.seo.keywords": "AI humanizer, humanize AI text, AI to human text converter, bypass AI detection, undetectable AI, GPTZero bypass, Turnitin bypass, ChatGPT humanizer",
  "ah.hero.title": "Humanize AI Text Instantly",
  "ah.hero.subtitle": "Transform AI-generated content into natural, undetectable human writing. Bypass every AI detector — GPTZero, Turnitin, Copyleaks & more.",
  "ah.hero.badge.free": "100% Free",
  "ah.hero.badge.undetectable": "Undetectable",
  "ah.hero.badge.modes": "6 Modes",
  "ah.hero.badge.words": "10,000 Words",
  "ah.hero.badge.streaming": "Live Streaming",
  "ah.input.placeholder": "Paste your AI-generated text here... (supports ChatGPT, Claude, Gemini, DeepSeek output)",
  "ah.input.panel_title": "AI-Generated Text",
  "ah.input.upload": "Upload File",
  "ah.input.upload.hint": "Supports TXT, PDF, DOCX (max 10MB)",
  "ah.mode.label": "Humanization Mode",
  "ah.mode.basic": "Basic",
  "ah.mode.basic.desc": "Light touch, fast, great for simple content",
  "ah.mode.standard": "Standard",
  "ah.mode.standard.desc": "Balanced rewrite, suits most content",
  "ah.mode.aggressive": "Aggressive",
  "ah.mode.aggressive.desc": "Deep rewrite, maximum undetectability",
  "ah.mode.academic": "Academic",
  "ah.mode.academic.desc": "Scholarly tone, preserves citations & structure",
  "ah.mode.creative": "Creative",
  "ah.mode.creative.desc": "Expressive, vivid, storytelling style",
  "ah.mode.business": "Business",
  "ah.mode.business.desc": "Professional, concise, corporate-ready",
  "ah.tone.label": "Writing Tone",
  "ah.tone.formal": "Formal",
  "ah.tone.casual": "Casual",
  "ah.tone.neutral": "Neutral",
  "ah.options.language": "Output Language",
  "ah.options.preserve_format": "Preserve Formatting",
  "ah.action.humanize": "Humanize Now",
  "ah.action.humanize.loading": "Humanizing...",
  "ah.action.detect": "Detect AI",
  "ah.action.detect.loading": "Detecting...",
  "ah.action.clear": "Clear All",
  "ah.action.copy": "Copy Text",
  "ah.action.copy.done": "Copied!",
  "ah.action.download.txt": "Download TXT",
  "ah.action.download.docx": "Download DOCX",
  "ah.action.humanize_again": "Humanize Again",
  "ah.status.streaming": "Generating human-like content...",
  "ah.status.done": "Humanization complete!",
  "ah.status.detecting": "Analyzing AI patterns...",
  "ah.result.panel_title": "Humanized Output",
  "ah.result.aiscore": "AI Score",
  "ah.result.readability": "Readability",
  "ah.result.empty": "Your humanized text will appear here...",
  "ah.history.title": "Recent History",
  "ah.history.empty": "No recent history",
  "ah.history.clear": "Clear History",
  "ah.history.restore": "Restore",
  "ah.error.too_long": "Text exceeds 10,000 words. Please shorten your input.",
  "ah.error.empty_input": "Please enter some text to humanize.",
  "ah.error.api_fail": "API request failed. Please check your connection and try again.",
  "ah.error.file_too_large": "File size exceeds 10MB limit.",
  "ah.error.unsupported_format": "Unsupported file format. Please use TXT, PDF, or DOCX.",
  "ah.feature.privacy.title": "100% Private",
  "ah.feature.privacy.desc": "Your text is processed securely and never stored on our servers.",
  "ah.feature.speed.title": "Lightning Fast",
  "ah.feature.speed.desc": "Real-time streaming output. See results appear as they're generated.",
  "ah.feature.free.title": "Forever Free",
  "ah.feature.free.desc": "No sign-up, no credit card. All 6 modes available free forever.",
  "ah.feature.multimode.title": "6 Expert Modes",
  "ah.feature.multimode.desc": "From basic rewrites to creative storytelling — a mode for every need.",
  "ah.faq.q1": "What is an AI Humanizer and how does it work?",
  "ah.faq.a1": "An AI Humanizer is a tool that rewrites AI-generated text to sound natural and human-like. Our tool analyzes patterns typical of AI writing and restructures the content using advanced language models, making it indistinguishable from human writing while preserving the original meaning.",
  "ah.faq.q2": "Which AI detectors can your tool bypass?",
  "ah.faq.a2": "Our AI Humanizer is designed to bypass all major AI detection tools including GPTZero, Turnitin, Copyleaks, ZeroGPT, Originality.ai, Winston AI, Sapling, and Scribbr. The Aggressive mode achieves the highest bypass rates.",
  "ah.faq.q3": "Is this tool completely free to use?",
  "ah.faq.a3": "Yes! All 6 humanization modes are 100% free with no word limits per session (up to 10,000 words per request). No account, no credit card, no hidden fees.",
  "ah.faq.q4": "What is the difference between the 6 humanization modes?",
  "ah.faq.a4": "Basic makes minimal changes for quick polishing. Standard balances quality and rewriting depth. Aggressive makes extensive restructuring for maximum undetectability. Academic preserves scholarly style and citations. Creative adds expressive flair. Business produces professional, formal output.",
  "ah.faq.q5": "Will humanizing my text change its meaning?",
  "ah.faq.a5": "Our tool is designed to preserve the core meaning, facts, and intent of your original text. It modifies sentence structure, word choice, and flow while keeping all key information intact.",
  "ah.faq.q6": "Does it support languages other than English?",
  "ah.faq.a6": "Yes! Our tool supports 12 languages including Chinese, Japanese, Korean, Spanish, French, German, Portuguese, Italian, Russian, Arabic, and Hindi.",
  "ah.faq.q7": "Can I upload PDF or Word documents?",
  "ah.faq.a7": "Absolutely. You can drag and drop or upload TXT, PDF, and DOCX files up to 10MB. The tool extracts the text and processes it directly.",
  "ah.faq.q8": "How does the real-time AI score work?",
  "ah.faq.a8": "Before humanizing, click 'Detect AI' to see the current AI probability score. After humanizing, the score automatically updates to show how much the AI detection risk has been reduced. Our target is always below 10% AI score.",
  "ah.nav.name": "AI Humanizer",
}

ZH_KEYS = {
  "ah.seo.title": "AI 文字人性化工具 — 免费将 AI 文字转为人类写作 | ToolboxNova",
  "ah.seo.desc": "一键将 ChatGPT、Claude、Gemini 生成的 AI 文字转化为自然的人类书写风格。绕过 GPTZero、Turnitin、Copyleaks 检测。6种模式，流式输出，永久免费。",
  "ah.seo.keywords": "AI文字人性化, AI转人工, 绕过AI检测, 反AI检测, ChatGPT人性化, Turnitin绕过, AI内容检测器",
  "ah.hero.title": "AI 文字人性化，一键完成",
  "ah.hero.subtitle": "将 AI 生成内容转化为自然、无法被检测的人类写作风格，绕过 GPTZero、Turnitin、Copyleaks 等一切 AI 检测器。",
  "ah.hero.badge.free": "完全免费",
  "ah.hero.badge.undetectable": "无法检测",
  "ah.hero.badge.modes": "6种模式",
  "ah.hero.badge.words": "10000字",
  "ah.hero.badge.streaming": "实时流式",
  "ah.input.placeholder": "在此粘贴 AI 生成的文字...（支持 ChatGPT、Claude、Gemini、DeepSeek 输出）",
  "ah.input.panel_title": "AI 生成的文字",
  "ah.input.upload": "上传文件",
  "ah.input.upload.hint": "支持 TXT、PDF、DOCX（最大 10MB）",
  "ah.mode.label": "人性化模式",
  "ah.mode.basic": "基础",
  "ah.mode.basic.desc": "轻度改写，速度快，适合简单内容",
  "ah.mode.standard": "标准",
  "ah.mode.standard.desc": "均衡改写，适合大多数内容",
  "ah.mode.aggressive": "激进",
  "ah.mode.aggressive.desc": "深度重构，最大程度绕过检测",
  "ah.mode.academic": "学术",
  "ah.mode.academic.desc": "学术风格，保留引用和结构",
  "ah.mode.creative": "创意",
  "ah.mode.creative.desc": "生动表达，叙事性强",
  "ah.mode.business": "商务",
  "ah.mode.business.desc": "专业简洁，适合商业场景",
  "ah.tone.label": "写作语调",
  "ah.tone.formal": "正式",
  "ah.tone.casual": "随性",
  "ah.tone.neutral": "中性",
  "ah.options.language": "输出语言",
  "ah.options.preserve_format": "保留格式",
  "ah.action.humanize": "立即人性化",
  "ah.action.humanize.loading": "人性化中...",
  "ah.action.detect": "检测 AI",
  "ah.action.detect.loading": "检测中...",
  "ah.action.clear": "清空全部",
  "ah.action.copy": "复制文本",
  "ah.action.copy.done": "已复制！",
  "ah.action.download.txt": "下载 TXT",
  "ah.action.download.docx": "下载 DOCX",
  "ah.action.humanize_again": "再次人性化",
  "ah.status.streaming": "正在生成人类风格内容...",
  "ah.status.done": "人性化完成！",
  "ah.status.detecting": "正在分析 AI 模式...",
  "ah.result.panel_title": "人性化输出",
  "ah.result.aiscore": "AI 分数",
  "ah.result.readability": "可读性",
  "ah.result.empty": "您的人性化文字将在此显示...",
  "ah.history.title": "最近记录",
  "ah.history.empty": "暂无历史记录",
  "ah.history.clear": "清空记录",
  "ah.history.restore": "恢复",
  "ah.error.too_long": "文字超过 10000 字，请缩短输入内容。",
  "ah.error.empty_input": "请输入需要人性化的文字。",
  "ah.error.api_fail": "API 请求失败，请检查网络连接后重试。",
  "ah.error.file_too_large": "文件大小超过 10MB 限制。",
  "ah.error.unsupported_format": "不支持的文件格式，请使用 TXT、PDF 或 DOCX。",
  "ah.feature.privacy.title": "100% 隐私安全",
  "ah.feature.privacy.desc": "您的文字安全处理，不存储在任何服务器上。",
  "ah.feature.speed.title": "极速响应",
  "ah.feature.speed.desc": "实时流式输出，文字生成即刻可见。",
  "ah.feature.free.title": "永久免费",
  "ah.feature.free.desc": "无需注册，无需信用卡，6 种模式全部免费。",
  "ah.feature.multimode.title": "6 种专业模式",
  "ah.feature.multimode.desc": "从基础改写到创意叙事，满足各类场景需求。",
  "ah.faq.q1": "什么是 AI 文字人性化工具，它如何工作？",
  "ah.faq.a1": "AI 文字人性化工具可以将 AI 生成的文字重写为自然的人类书写风格。我们的工具分析 AI 写作的典型模式，并使用先进的语言模型重构内容，使其与人类写作无法区分，同时保留原始含义。",
  "ah.faq.q2": "你们的工具能绕过哪些 AI 检测器？",
  "ah.faq.a2": "我们的 AI 人性化工具可绕过所有主流 AI 检测工具，包括 GPTZero、Turnitin、Copyleaks、ZeroGPT、Originality.ai、Winston AI、Sapling 和 Scribbr。激进模式可实现最高绕过率。",
  "ah.faq.q3": "这个工具完全免费吗？",
  "ah.faq.a3": "是的！所有 6 种人性化模式 100% 免费，每次请求最多支持 10000 字。无需账号，无需信用卡，没有任何隐藏费用。",
  "ah.faq.q4": "6 种人性化模式有什么区别？",
  "ah.faq.a4": "基础模式做最小改动，适合快速润色。标准模式均衡改写，适合大多数内容。激进模式深度重构，最大程度绕过检测。学术模式保留学术风格和引用。创意模式增添生动表达。商务模式输出专业正式的内容。",
  "ah.faq.q5": "人性化处理会改变文字的含义吗？",
  "ah.faq.a5": "我们的工具旨在保留原始文字的核心含义、事实和意图。它修改句子结构、词语选择和行文流畅度，同时保持所有关键信息完整。",
  "ah.faq.q6": "支持中文以外的语言吗？",
  "ah.faq.a6": "支持！我们的工具支持 12 种语言，包括英语、日语、韩语、西班牙语、法语、德语、葡萄牙语、意大利语、俄语、阿拉伯语和印地语。",
  "ah.faq.q7": "可以上传 PDF 或 Word 文档吗？",
  "ah.faq.a7": "完全可以。您可以拖拽或上传 TXT、PDF 和 DOCX 文件（最大 10MB）。工具会自动提取文字并进行处理。",
  "ah.faq.q8": "实时 AI 分数是如何工作的？",
  "ah.faq.a8": "人性化前点击「检测 AI」可查看当前 AI 概率分数。人性化后，分数会自动更新，显示 AI 检测风险降低了多少。我们的目标是始终将 AI 分数控制在 10% 以下。",
  "ah.nav.name": "AI 人性化",
}

JA_KEYS = {
  "ah.seo.title": "AI文章人間化ツール — AIテキストを自然な人間の文章に無料変換 | ToolboxNova",
  "ah.seo.desc": "ChatGPT・Claude・GeminiのAIテキストを自然な人間文体に変換。GPTZero・Turnitin・Copyleaksを回避。6モード、ストリーミング出力、永久無料。",
  "ah.seo.keywords": "AI人間化, AIテキスト変換, AI検出回避, GPTZero回避, Turnitin回避",
  "ah.hero.title": "AIテキストを即座に人間化",
  "ah.hero.subtitle": "AI生成コンテンツを自然で検出不可能な人間の文章に変換。GPTZero、Turnitin、Copyleaksなどすべての検出ツールを回避します。",
  "ah.hero.badge.free": "完全無料",
  "ah.hero.badge.undetectable": "検出不可",
  "ah.hero.badge.modes": "6モード",
  "ah.hero.badge.words": "10000語",
  "ah.hero.badge.streaming": "ライブ出力",
  "ah.input.placeholder": "AIが生成したテキストをここに貼り付けてください...",
  "ah.input.panel_title": "AI生成テキスト",
  "ah.input.upload": "ファイルをアップロード",
  "ah.input.upload.hint": "TXT、PDF、DOCXに対応（最大10MB）",
  "ah.mode.label": "人間化モード",
  "ah.mode.basic": "ベーシック",
  "ah.mode.basic.desc": "軽微な変更、高速、シンプルなコンテンツに最適",
  "ah.mode.standard": "スタンダード",
  "ah.mode.standard.desc": "バランスの取れた書き直し、ほとんどのコンテンツに適合",
  "ah.mode.aggressive": "アグレッシブ",
  "ah.mode.aggressive.desc": "徹底的な書き直し、最大限の検出回避",
  "ah.mode.academic": "学術",
  "ah.mode.academic.desc": "学術的なトーン、引用と構造を保持",
  "ah.mode.creative": "クリエイティブ",
  "ah.mode.creative.desc": "表現豊か、生き生きとした語り口",
  "ah.mode.business": "ビジネス",
  "ah.mode.business.desc": "プロフェッショナル、簡潔、ビジネス向け",
  "ah.tone.label": "文体トーン",
  "ah.tone.formal": "フォーマル",
  "ah.tone.casual": "カジュアル",
  "ah.tone.neutral": "ニュートラル",
  "ah.options.language": "出力言語",
  "ah.options.preserve_format": "フォーマットを保持",
  "ah.action.humanize": "今すぐ人間化",
  "ah.action.humanize.loading": "人間化中...",
  "ah.action.detect": "AI検出",
  "ah.action.detect.loading": "検出中...",
  "ah.action.clear": "すべてクリア",
  "ah.action.copy": "テキストをコピー",
  "ah.action.copy.done": "コピーしました！",
  "ah.action.download.txt": "TXTをダウンロード",
  "ah.action.download.docx": "DOCXをダウンロード",
  "ah.action.humanize_again": "再度人間化",
  "ah.status.streaming": "人間らしいコンテンツを生成中...",
  "ah.status.done": "人間化完了！",
  "ah.status.detecting": "AIパターンを分析中...",
  "ah.result.panel_title": "人間化された出力",
  "ah.result.aiscore": "AIスコア",
  "ah.result.readability": "読みやすさ",
  "ah.result.empty": "人間化されたテキストがここに表示されます...",
  "ah.history.title": "最近の履歴",
  "ah.history.empty": "履歴なし",
  "ah.history.clear": "履歴をクリア",
  "ah.history.restore": "復元",
  "ah.error.too_long": "テキストが10,000語を超えています。入力を短くしてください。",
  "ah.error.empty_input": "人間化するテキストを入力してください。",
  "ah.error.api_fail": "APIリクエストに失敗しました。接続を確認して再試行してください。",
  "ah.error.file_too_large": "ファイルサイズが10MBの制限を超えています。",
  "ah.error.unsupported_format": "サポートされていないファイル形式です。TXT、PDF、またはDOCXを使用してください。",
  "ah.feature.privacy.title": "100%プライベート",
  "ah.feature.privacy.desc": "テキストは安全に処理され、サーバーには保存されません。",
  "ah.feature.speed.title": "超高速",
  "ah.feature.speed.desc": "リアルタイムストリーミング出力。生成と同時に結果が表示されます。",
  "ah.feature.free.title": "永久無料",
  "ah.feature.free.desc": "登録不要、クレジットカード不要。6つのモードすべて永久無料。",
  "ah.feature.multimode.title": "6つの専門モード",
  "ah.feature.multimode.desc": "基本的な書き直しからクリエイティブなストーリーテリングまで。",
  "ah.faq.q1": "AI人間化ツールとは何ですか？",
  "ah.faq.a1": "AI人間化ツールは、AI生成テキストを自然な人間の文体に書き換えるツールです。当ツールはAI文章の典型的なパターンを分析し、高度な言語モデルを使用してコンテンツを再構築します。",
  "ah.faq.q2": "どのAI検出ツールを回避できますか？",
  "ah.faq.a2": "GPTZero、Turnitin、Copyleaks、ZeroGPT、Originality.ai、Winston AI、Sapling、Scribbr など主要なAI検出ツールをすべて回避するよう設計されています。",
  "ah.faq.q3": "完全無料で使えますか？",
  "ah.faq.a3": "はい！6つの人間化モードすべて100%無料です。1回のリクエストで最大10,000語まで対応。アカウント不要、クレジットカード不要。",
  "ah.faq.q4": "6つのモードの違いは何ですか？",
  "ah.faq.a4": "ベーシックは最小限の変更、スタンダードはバランス、アグレッシブは最大限の書き直し、学術は引用を保持、クリエイティブは表現を豊かに、ビジネスはプロ向けです。",
  "ah.faq.q5": "人間化するとテキストの意味が変わりますか？",
  "ah.faq.a5": "元のテキストの核心的な意味、事実、意図を保持するよう設計されています。文の構造、語彙選択、流れを変更しますが、重要な情報はすべて維持されます。",
  "ah.faq.q6": "英語以外の言語に対応していますか？",
  "ah.faq.a6": "はい！中国語、日本語、韓国語、スペイン語、フランス語、ドイツ語、ポルトガル語、イタリア語、ロシア語、アラビア語、ヒンディー語を含む12言語に対応しています。",
  "ah.faq.q7": "PDFやWordファイルをアップロードできますか？",
  "ah.faq.a7": "できます。TXT、PDF、DOCXファイル（最大10MB）をドラッグ&ドロップまたはアップロードできます。",
  "ah.faq.q8": "リアルタイムAIスコアとは何ですか？",
  "ah.faq.a8": "人間化前に「AI検出」をクリックすると現在のAI確率スコアが表示されます。人間化後、スコアが自動的に更新され、AI検出リスクがどれだけ低下したかがわかります。",
  "ah.nav.name": "AI人間化",
}

KO_KEYS = {
  "ah.seo.title": "AI 텍스트 인간화 도구 — AI 글을 자연스러운 인간 글쓰기로 무료 변환 | ToolboxNova",
  "ah.seo.desc": "ChatGPT, Claude, Gemini AI 텍스트를 자연스러운 인간 글쓰기로 변환. GPTZero, Turnitin, Copyleaks 우회. 6가지 모드, 스트리밍 출력, 영구 무료.",
  "ah.seo.keywords": "AI 인간화, AI 텍스트 변환, AI 감지 우회, GPTZero 우회, Turnitin 우회",
  "ah.hero.title": "AI 텍스트를 즉시 인간화",
  "ah.hero.subtitle": "AI 생성 콘텐츠를 자연스럽고 감지 불가능한 인간 글쓰기로 변환합니다. GPTZero, Turnitin, Copyleaks 등 모든 AI 감지 도구를 우회하세요.",
  "ah.hero.badge.free": "완전 무료",
  "ah.hero.badge.undetectable": "감지 불가",
  "ah.hero.badge.modes": "6가지 모드",
  "ah.hero.badge.words": "10,000 단어",
  "ah.hero.badge.streaming": "실시간 스트리밍",
  "ah.input.placeholder": "여기에 AI 생성 텍스트를 붙여넣으세요...",
  "ah.input.panel_title": "AI 생성 텍스트",
  "ah.input.upload": "파일 업로드",
  "ah.input.upload.hint": "TXT, PDF, DOCX 지원 (최대 10MB)",
  "ah.mode.label": "인간화 모드",
  "ah.mode.basic": "기본",
  "ah.mode.basic.desc": "가벼운 수정, 빠름, 간단한 콘텐츠에 적합",
  "ah.mode.standard": "표준",
  "ah.mode.standard.desc": "균형 잡힌 재작성, 대부분의 콘텐츠에 적합",
  "ah.mode.aggressive": "공격적",
  "ah.mode.aggressive.desc": "심층 재작성, 최대 감지 불가능성",
  "ah.mode.academic": "학술",
  "ah.mode.academic.desc": "학술적 어조, 인용 및 구조 보존",
  "ah.mode.creative": "창의적",
  "ah.mode.creative.desc": "표현력 풍부, 생생한 스토리텔링",
  "ah.mode.business": "비즈니스",
  "ah.mode.business.desc": "전문적, 간결, 기업용",
  "ah.tone.label": "글쓰기 어조",
  "ah.tone.formal": "격식체",
  "ah.tone.casual": "비격식체",
  "ah.tone.neutral": "중립",
  "ah.options.language": "출력 언어",
  "ah.options.preserve_format": "서식 보존",
  "ah.action.humanize": "지금 인간화",
  "ah.action.humanize.loading": "인간화 중...",
  "ah.action.detect": "AI 감지",
  "ah.action.detect.loading": "감지 중...",
  "ah.action.clear": "모두 지우기",
  "ah.action.copy": "텍스트 복사",
  "ah.action.copy.done": "복사됨!",
  "ah.action.download.txt": "TXT 다운로드",
  "ah.action.download.docx": "DOCX 다운로드",
  "ah.action.humanize_again": "다시 인간화",
  "ah.status.streaming": "인간다운 콘텐츠 생성 중...",
  "ah.status.done": "인간화 완료!",
  "ah.status.detecting": "AI 패턴 분석 중...",
  "ah.result.panel_title": "인간화된 출력",
  "ah.result.aiscore": "AI 점수",
  "ah.result.readability": "가독성",
  "ah.result.empty": "인간화된 텍스트가 여기에 표시됩니다...",
  "ah.history.title": "최근 기록",
  "ah.history.empty": "기록 없음",
  "ah.history.clear": "기록 지우기",
  "ah.history.restore": "복원",
  "ah.error.too_long": "텍스트가 10,000 단어를 초과합니다. 입력을 줄여주세요.",
  "ah.error.empty_input": "인간화할 텍스트를 입력해주세요.",
  "ah.error.api_fail": "API 요청에 실패했습니다. 연결을 확인하고 다시 시도해주세요.",
  "ah.error.file_too_large": "파일 크기가 10MB 제한을 초과합니다.",
  "ah.error.unsupported_format": "지원되지 않는 파일 형식입니다. TXT, PDF 또는 DOCX를 사용해주세요.",
  "ah.feature.privacy.title": "100% 비공개",
  "ah.feature.privacy.desc": "텍스트는 안전하게 처리되며 서버에 저장되지 않습니다.",
  "ah.feature.speed.title": "초고속",
  "ah.feature.speed.desc": "실시간 스트리밍 출력. 생성되는 대로 결과가 표시됩니다.",
  "ah.feature.free.title": "영구 무료",
  "ah.feature.free.desc": "가입 불필요, 신용카드 불필요. 6가지 모드 모두 영구 무료.",
  "ah.feature.multimode.title": "6가지 전문 모드",
  "ah.feature.multimode.desc": "기본 재작성부터 창의적인 스토리텔링까지.",
  "ah.faq.q1": "AI 인간화 도구란 무엇인가요?",
  "ah.faq.a1": "AI 인간화 도구는 AI가 생성한 텍스트를 자연스러운 인간 글쓰기 스타일로 다시 작성하는 도구입니다.",
  "ah.faq.q2": "어떤 AI 감지 도구를 우회할 수 있나요?",
  "ah.faq.a2": "GPTZero, Turnitin, Copyleaks, ZeroGPT, Originality.ai, Winston AI 등 주요 AI 감지 도구를 모두 우회하도록 설계되었습니다.",
  "ah.faq.q3": "완전히 무료인가요?",
  "ah.faq.a3": "네! 6가지 인간화 모드 모두 100% 무료입니다. 계정, 신용카드, 숨겨진 요금 없이 이용 가능합니다.",
  "ah.faq.q4": "6가지 모드의 차이는 무엇인가요?",
  "ah.faq.a4": "기본은 최소한의 변경, 표준은 균형 잡힌 재작성, 공격적은 최대 재구성, 학술은 학술 스타일 보존, 창의적은 표현력 추가, 비즈니스는 전문적 출력입니다.",
  "ah.faq.q5": "인간화하면 의미가 바뀌나요?",
  "ah.faq.a5": "원본 텍스트의 핵심 의미, 사실, 의도를 보존하도록 설계되었습니다.",
  "ah.faq.q6": "영어 외 다른 언어도 지원하나요?",
  "ah.faq.a6": "네! 중국어, 일본어, 한국어, 스페인어 등 12개 언어를 지원합니다.",
  "ah.faq.q7": "PDF나 Word 파일을 업로드할 수 있나요?",
  "ah.faq.a7": "물론입니다. TXT, PDF, DOCX 파일(최대 10MB)을 드래그 앤 드롭하거나 업로드할 수 있습니다.",
  "ah.faq.q8": "실시간 AI 점수는 어떻게 작동하나요?",
  "ah.faq.a8": "인간화 전에 'AI 감지'를 클릭하면 현재 AI 확률 점수를 볼 수 있습니다. 인간화 후 점수가 자동으로 업데이트됩니다.",
  "ah.nav.name": "AI 인간화",
}

SPA_KEYS = {
  "ah.seo.title": "Humanizador de IA — Convierte Texto IA en Escritura Humana Gratis | ToolboxNova",
  "ah.seo.desc": "Transforma texto de ChatGPT, Claude, Gemini en escritura humana natural. Evita GPTZero, Turnitin, Copyleaks. 6 modos, salida en streaming, gratis para siempre.",
  "ah.seo.keywords": "humanizador de IA, convertir texto IA, evadir detección IA, bypass GPTZero, bypass Turnitin",
  "ah.hero.title": "Humaniza Texto IA al Instante",
  "ah.hero.subtitle": "Transforma contenido generado por IA en escritura humana natural e indetectable. Evita GPTZero, Turnitin, Copyleaks y todos los detectores de IA.",
  "ah.hero.badge.free": "100% Gratis",
  "ah.hero.badge.undetectable": "Indetectable",
  "ah.hero.badge.modes": "6 Modos",
  "ah.hero.badge.words": "10.000 Palabras",
  "ah.hero.badge.streaming": "Transmisión en Vivo",
  "ah.input.placeholder": "Pega aquí tu texto generado por IA...",
  "ah.input.panel_title": "Texto Generado por IA",
  "ah.input.upload": "Subir Archivo",
  "ah.input.upload.hint": "Compatible con TXT, PDF, DOCX (máx. 10MB)",
  "ah.mode.label": "Modo de Humanización",
  "ah.mode.basic": "Básico",
  "ah.mode.basic.desc": "Cambios mínimos, rápido, ideal para contenido simple",
  "ah.mode.standard": "Estándar",
  "ah.mode.standard.desc": "Reescritura equilibrada, ideal para la mayoría del contenido",
  "ah.mode.aggressive": "Agresivo",
  "ah.mode.aggressive.desc": "Reescritura profunda, máxima indetectabilidad",
  "ah.mode.academic": "Académico",
  "ah.mode.academic.desc": "Tono académico, preserva citas y estructura",
  "ah.mode.creative": "Creativo",
  "ah.mode.creative.desc": "Expresivo, vívido, estilo narrativo",
  "ah.mode.business": "Empresarial",
  "ah.mode.business.desc": "Profesional, conciso, listo para negocios",
  "ah.tone.label": "Tono de Escritura",
  "ah.tone.formal": "Formal",
  "ah.tone.casual": "Casual",
  "ah.tone.neutral": "Neutral",
  "ah.options.language": "Idioma de Salida",
  "ah.options.preserve_format": "Preservar Formato",
  "ah.action.humanize": "Humanizar Ahora",
  "ah.action.humanize.loading": "Humanizando...",
  "ah.action.detect": "Detectar IA",
  "ah.action.detect.loading": "Detectando...",
  "ah.action.clear": "Borrar Todo",
  "ah.action.copy": "Copiar Texto",
  "ah.action.copy.done": "¡Copiado!",
  "ah.action.download.txt": "Descargar TXT",
  "ah.action.download.docx": "Descargar DOCX",
  "ah.action.humanize_again": "Humanizar de Nuevo",
  "ah.status.streaming": "Generando contenido humano...",
  "ah.status.done": "¡Humanización completa!",
  "ah.status.detecting": "Analizando patrones de IA...",
  "ah.result.panel_title": "Salida Humanizada",
  "ah.result.aiscore": "Puntuación IA",
  "ah.result.readability": "Legibilidad",
  "ah.result.empty": "Tu texto humanizado aparecerá aquí...",
  "ah.history.title": "Historial Reciente",
  "ah.history.empty": "Sin historial",
  "ah.history.clear": "Borrar Historial",
  "ah.history.restore": "Restaurar",
  "ah.error.too_long": "El texto supera 10.000 palabras. Por favor acorta tu entrada.",
  "ah.error.empty_input": "Por favor introduce texto para humanizar.",
  "ah.error.api_fail": "Error en la solicitud API. Verifica tu conexión e inténtalo de nuevo.",
  "ah.error.file_too_large": "El archivo supera el límite de 10MB.",
  "ah.error.unsupported_format": "Formato de archivo no soportado. Usa TXT, PDF o DOCX.",
  "ah.feature.privacy.title": "100% Privado",
  "ah.feature.privacy.desc": "Tu texto se procesa de forma segura y nunca se almacena en nuestros servidores.",
  "ah.feature.speed.title": "Ultrarrápido",
  "ah.feature.speed.desc": "Salida en streaming en tiempo real. Los resultados aparecen conforme se generan.",
  "ah.feature.free.title": "Gratis Para Siempre",
  "ah.feature.free.desc": "Sin registro, sin tarjeta de crédito. Los 6 modos disponibles gratis para siempre.",
  "ah.feature.multimode.title": "6 Modos Expertos",
  "ah.feature.multimode.desc": "Desde reescrituras básicas hasta narrativas creativas.",
  "ah.faq.q1": "¿Qué es un humanizador de IA y cómo funciona?",
  "ah.faq.a1": "Un humanizador de IA reescribe texto generado por IA para que suene natural y humano.",
  "ah.faq.q2": "¿Qué detectores de IA puede evadir?",
  "ah.faq.a2": "GPTZero, Turnitin, Copyleaks, ZeroGPT, Originality.ai, Winston AI y otros detectores principales.",
  "ah.faq.q3": "¿Es completamente gratuito?",
  "ah.faq.a3": "¡Sí! Los 6 modos son 100% gratuitos sin límites de palabras por sesión.",
  "ah.faq.q4": "¿Cuál es la diferencia entre los 6 modos?",
  "ah.faq.a4": "Básico hace cambios mínimos. Estándar equilibra calidad. Agresivo hace reestructuración máxima. Académico preserva citas. Creativo añade expresividad. Empresarial produce salida profesional.",
  "ah.faq.q5": "¿Humanizar el texto cambia su significado?",
  "ah.faq.a5": "La herramienta preserva el significado central, los hechos y la intención del texto original.",
  "ah.faq.q6": "¿Admite otros idiomas además del español?",
  "ah.faq.a6": "¡Sí! Admite 12 idiomas incluyendo chino, japonés, coreano, inglés y más.",
  "ah.faq.q7": "¿Puedo subir archivos PDF o Word?",
  "ah.faq.a7": "Por supuesto. Puedes arrastrar y soltar o subir archivos TXT, PDF y DOCX (hasta 10MB).",
  "ah.faq.q8": "¿Cómo funciona la puntuación de IA en tiempo real?",
  "ah.faq.a8": "Antes de humanizar, haz clic en 'Detectar IA' para ver la puntuación de probabilidad actual. Después de humanizar, la puntuación se actualiza automáticamente.",
  "ah.nav.name": "AI Humanizador",
}

LANG_MAP = {
    'en.json': EN_KEYS,
    'zh.json': ZH_KEYS,
    'ja.json': JA_KEYS,
    'ko.json': KO_KEYS,
    'spa.json': SPA_KEYS,
}

for fname, new_keys in LANG_MAP.items():
    fpath = os.path.join(BASE, fname)
    with open(fpath, encoding='utf-8') as f:
        data = json.load(f)
    # Only add keys that don't exist yet
    added = 0
    for k, v in new_keys.items():
        if k not in data:
            data[k] = v
            added += 1
    with open(fpath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"{fname}: added {added} keys, total {len(data)}")

print("Done!")

